name: Deployment

on:
  push:
    branches:
      - master
      
jobs:
  deploynetlify:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: create deployment
      uses: niklasmerz/github-deployment-action@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: -o venclave -r venclave.com -c master -e production
    
    - name: set deployment success
      uses: niklasmerz/github-deployment-action@v1.0.0
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: -o venclave -r venclave.com -s success -u https://venclave.com -f
        
    - name: set deployment failure
      uses: niklasmerz/github-deployment-action@v1.0.0
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: -o venclave -r venclave.com -s failure -u https://venclave.com -f
